%% load data
if exist('source_data_dir','var')
    load([source_data_dir '/fig2_efgh.mat'])
end
%% figure
clf
hold on
boxplot([ft_cmp_emp.exp_power_v_exp(:,1)...
    ft_cmp_emp.power_v_exp(:,1) ft_cmp_emp.power_v_exp_power(:,1)])
plot([...
    ones(length(eigmax),1)...
    2*ones(length(eigmax),1)...
    3*ones(length(eigmax),1)],...
    [...
    ft_cmp_emp.exp_power_v_exp(:,1)...
    ft_cmp_emp.power_v_exp(:,1)...
    ft_cmp_emp.power_v_exp_power(:,1)],...
    'k.')
prettify
xticklabels({'ep v e','p v e','p v ep'})
ft_cmp_emp
disp(max([ft_cmp_emp.exp_power_v_exp(:,2)...
    ft_cmp_emp.power_v_exp(:,2)...
    ft_cmp_emp.power_v_exp_power(:,2)]))
