%% generate binary synthetic networks
sn_b = {...
    net.generate('erdosrenyi','n',2^12,'p',.06,'dir',true),...
    net.generate('erdosrenyi','n',2^12,'p',.1,'dir',true),...
    net.generate('erdosrenyi','n',2^12,'p',.14,'dir',true),...
    net.generate('erdosrenyi','n',2^12,'p',.18,'dir',true),...
    net.generate('hiermodsmallworld','mx_lvl',12,'e',1.39,'sz_cl',2),...
    net.generate('hiermodsmallworld','mx_lvl',12,'e',1.3,'sz_cl',2),...
    net.generate('hiermodsmallworld','mx_lvl',12,'e',1.25,'sz_cl',2),...
    net.generate('hiermodsmallworld','mx_lvl',12,'e',1.22,'sz_cl',2),...
    net.generate('wattsstrogatz','n',2^12,'k',2^8,'p',.5,'dir',true),...
    net.generate('wattsstrogatz','n',2^12,'k',2^8+2^7,'p',.5,'dir',true),...
    net.generate('wattsstrogatz','n',2^12,'k',2^9+2^6,'p',.5,'dir',true),...
    net.generate('wattsstrogatz','n',2^12,'k',2^9+2^7,'p',.5,'dir',true),...
    net.generate('modular','n',2^12,'k',int32(2^24*.03),'m',4,'p',0.8,...
        'dir',true),...
    net.generate('modular','n',2^12,'k',int32(2^24*.05),'m',4,'p',0.8,...
        'dir',true),...
    net.generate('modular','n',2^12,'k',int32(2^24*.07),'m',4,'p',0.8,...
        'dir',true),...
    net.generate('modular','n',2^12,'k',int32(2^24*.09),'m',4,'p',0.8,...
        'dir',true),...
    };
sn_fc = zeros(length(sn_b),1);
for i = 1 : length(sn_b)
    sn_fc(i) = nnz(sn_b{i}.A)/size(sn_b{i}.A,1)^2;
end; clear i
%% set weight parameters
sn_tw = 4;
sn_sig = repmat(1e-3:1e-3:3e-3,[1 sn_tw]);